Tienda/Tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('users/',include('users.urls')),
]

Tienda/store/urls.py
from django.urls import path,re_path

from . import views

app_name='store'
urlpatterns=[
    re_path('^new/$',views.newProduct,name='newProduct'),
    re_path('',views.viewProducts,name='viewProducts'),
    re_path('^view/<int:id>$',views.detailProduct,name='viewDetailProduct'),
    re_path('^delete/<int:id>$',views.deleteProduct,name='deleteProduct'),
    re_path('^update/<int:id>$',views.updateProduct,name='updateProduct'),
    re_path('^whishlist/<int:id>$',views.wishlistProduct,name='wishlistProduct'),
    re_path('^addToCart/<int:id>$',views.purchaseProduct,name='addToCart'),
    re_path('cart/', views.cart, name='cart'),
    re_path('transaction/', views.transactionPanel, name='transactionPanel'),

]

Tienda/users/urls.py
from django.urls import path,re_path
from . import views

app_name='users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('', views.user_login, name='index'),
]

Tienda/store/models.py
from django.db import models
from django.contrib.auth.models import User

class gafas(models.Model):
    ItemId=models.BigAutoField(primary_key=True)
    ItemName=models.TextField(max_length=255)
    ItemCategory=models.TextField(max_length=255)
    Price=models.IntegerField()


class bodega(models.Model):
    ItemId=models.ManyToManyField(gafas, related_name="bodega_gafas")
    BodegaID=models.BigAutoField(primary_key=True)
    location=models.TextField(max_length=100)
    ItemStock=models.IntegerField()


class wishlist(models.Model):
    WishlistID=models.BigAutoField(primary_key=True)
    User=models.ForeignKey(
        User,
        on_delete=models.CASCADE)
    ItemsId=models.ManyToManyField(gafas , related_name="wishlist_gafas")


class Order(models.Model):
    APROBADA='1'
    PENDIENTE='2'
    DENEGADA='3'

    STATUS_CHOICES=[
        (APROBADA,'aprobada'),
        (PENDIENTE,'pendiente'),
        (DENEGADA,'denegada'),
    ]

    orderID=models.AutoField(primary_key=True)
    status=models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default=PENDIENTE,
        )
    address=models.TextField(max_length=255)
    products=models.ManyToManyField (gafas, related_name="orden_gafas")

Tienda/users/models.py
from django.db import models

class user:
    pass

Tienda/store/forms.py
from django import forms
from .import models

class CreateProducts(forms.ModelForm):
    class Meta:
        model=models.gafas
        fields=['ItemName','ItemCategory','Price']

class bodega(forms.ModelForm):
    class Meta:
        model=models.bodega
        fields=['BodegaID','location','ItemStock']


Tienda/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=False)  # Quita la restricción del email
    password1 = forms.CharField(
        label="Contraseña",
        strip=False,
        widget=forms.PasswordInput,
        help_text="",
    )
    password2 = forms.CharField(
        label="Confirmar contraseña",
        strip=False,
        widget=forms.PasswordInput,
        help_text="",
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {
            'username': None,  # Quita el texto de ayuda del username
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        return password2

Tienda/store/views.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import gafas
from . import forms



home='store:view'

#handles creation of new products 
def newProduct(request):
    if request.method == "POST":
        form = forms.CreateProducts(request.POST)
        if form.is_valid():
            form.save()
            return redirect('store:viewProducts')
    else:
        form = forms.CreateProducts()
    return render(request,'newProduct.html',{'form': form})


#handles view of individual products

def viewProducts(request):
    if request.method == "GET":
        Gafas=gafas
        return render(request,'store:viewProduct.html',Gafas)
    else:
        pass
    return render(request,'store:viewProduct.html')

def viewProducts(request):
    if request.method == "GET":
        Gafas=gafas.objects.all()
        return render(request,'viewProduct.html',{'gafas':Gafas})
    else:
        pass
    return render(request,'viewProduct.html',{"Gafas":gafas})



def detailProduct(request,id):
    def get(request):
        product=gafas.objects.get(ItemId=id)
        return render (request,'store/productDetail.html',{'product':product})

#handles deletion of new products
def deleteProduct(view):
    def get(self,**kwargs):
        pass

def updateProduct(request, id):
    product = gafas.objects.get(ItemId=id)
    if request.method == 'POST':
        form = forms.CreateProducts(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(home)
    else:
        form = forms.CreateProducts(instance=product)
    return render(request, 'store/newProduct.html', {'form': form})

def purchaseProduct(request,id):
    def post(self,request,id):
        product=gafas.objects.get(ItemId=id)
        

#handles updates of products


#handles the process to add on a whislist a product 
def wishlistProduct(request, id):
    pass
 
def purchaseProduct():
    pass

def cart(request):
    return render(request, 'store:cart.html')

def transactionPanel(request):
    return render(request, 'store:transaction.html')

Tienda/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout
#premade user form created by django
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
#local
from .models import  user
from .forms import UserRegisterForm
from django.contrib.auth import login, authenticate 
from django.contrib import messages



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, f'Usuario {username} creado exitosamente.')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:viewProduct')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form, "title": "SumEye"})

def logout_view(request):
    if (request.method=='POST'):
        logout(request)
        return redirect('users:login')

Tienda/store/templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carrito</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="cart-container">
        <div class="cart-items">
            <p>Tu carrito está vacío.</p>
        </div>
        <div class="cart-actions">
            <form action="{% url 'store:purchase' %}" method="post">
                {% csrf_token %}
                <button type="submit">Comprar</button>
            </form>
        </div>
    </div>
</body>
</html>

Tienda/store/templates/newProduct.html
{%extends 'base.html'%}
{%block content%}
<div class="create-product">
  <h2>create task</h2>
  <form class="newProduct" action="{%url 'store:newProduct'%}" method="post">
    {%csrf_token%}
    {{form}}
    <input type="submit" name="" value="create">
  </form>
</div>
{%endblock%}

Tienda/store/templates/productDetail.html
{%extends 'base.html'%}
{%block content%}
<div class="product">
  <h2>{{product.ItemName}}</h2>
  <p>{{product.ItemCategory}}</p>
  <p>{{product.Price}}</p>
  <form method="post" action="{% url 'store:addToCart' id=products.ItemId%}">>
    {% csrf_token %}
    <button type="submit">añadir al carrito</button>
</div>
{%endblock%}

Tienda/store/templates/transaction.html
{% extends 'base.html' %}

{% block content %}
<div class="transaction-panel">
    <h2>Panel de Transacción</h2>
    <button onclick="alert('Botón presionado!')">Hacer Transacción</button>
</div>
{% endblock %}

Tienda/store/templates/viewProduct.html
{%extends 'base.html'%}
    {%block content%}
    <div class="products"></div>

      </div>
        {% csrf_token %}
    </form>
    {%endblock%}

Tienda/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>Venta de lentes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .container h2 {
            margin-bottom: 20px;
            color: #ff7f50;
        }

        .container form {
            display: flex;
            flex-direction: column;
        }

        .container form input {
            margin-bottom: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .container form button {
            padding: 10px;
            border: none;
            border-radius: 4px;
            background-color: #ff7f50;
            color: #fff;
            cursor: pointer;
        }

        .container form button:hover {
            background-color: #ff4500;
        }

        .register-link {
            margin-top: 20px;
        }

        .register-link a {
            color: #ff7f50;
            text-decoration: none;
            transition: color 0.3s ease;
        }

        .register-link a:hover {
            color: #ff4500;
        }
    </style>
</head>

<body>
    <h1>store</h1>
    {% block content %}
    {% endblock %}
</body>

</html>

Tienda/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Registro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .container h2 {
            margin-bottom: 20px;
            color: #ff7f50;
        }
        .container form {
            display: flex;
            flex-direction: column;
        }
        .container form input {
            margin-bottom: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .container form button {
            padding: 10px;
            border: none;
            border-radius: 4px;
            background-color: #ff7f50;
            color: #fff;
            cursor: pointer;
        }
        .container form button:hover {
            background-color: #ff4500;
        }
        .messages {
            margin-bottom: 20px;
            color: green;
        }
    </style>
</head>
<body>

</body>
</html>

Tienda/templates/wishlist.html
<!DOCTYPE html>
<html>
<head>
    <title>Wishlist</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .container h2 {
            margin-bottom: 20px;
            color: #ff7f50;
        }
        .wishlist-item {
            margin-bottom: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Mi Wishlist</h2>
        {% if wishlist %}
            {% for item in wishlist.ItemsId.all %}
                <div class="wishlist-item">
                    <p>{{ item.ItemName }}</p>
                    <p>{{ item.ItemCategory }}</p>
                    <p>{{ item.Price }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No tienes ningún artículo en tu wishlist.</p>
        {% endif %}
    </div>
</body>
</html>

Tienda/users/templates/login.html
{%extends 'base.html'%}

{%block content%}
  <p>log in</p>
  <div class="container">
    <h2>SumEye</h2>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar sesión</button>
    </form>
    <div class="register-link">
        <p>¿Aún no estás registrado? <a href="{% url 'users:register' %}">Regístrate aquí</a></p>
    </div>
</div>
{%endblock%}

Tienda/users/templates/register.html
{%extends 'base.html'%}

{% block content %}
<div class="container">
    <h2>Registro</h2>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
</div>
{% endblock content %}